server:
 servlet:
  context-path: /
 port: 8765

spring:
# devtools:
#  livereload:
#   enabled: true
#  thymeleaf:
#   cache: false
 autoconfigure:
  exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

 application:
  name: booter

 datasource:
  url: jdbc:mysql://192.168.45.195:3306/booter?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul
  username: donggeol
  password: yi109304
  driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
   auto-commit: false
   connection-test-query: SELECT 1
   minimum-idle: 10
   maximum-pool-size: 50
   transaction-isolation: TRANSACTION_READ_UNCOMMITTED
   pool-name: pool-booter

 jpa:
  open-in-view : false
  database: mysql
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  properties:
   hibernate:
    format_sql: true
    show_sql: true
  generate-ddl: true
  hibernate:
#   ddl-auto: create-drop
   ddl-auto: update

 profiles:
  active: local

jwt:
 base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=

logging:
 level:
#  web: DEBUG
  org:
   springframework:
    security: DEBUG
    data: DEBUG



